### ISSUE TITLE
401 Unauthorized using FlowFuse

### ISSUE THREAD

**Issue by 78wesley** [node-red-jp/node-red-contrib-plugin-chatgpt#4]
Hi, I've a little problem with this plugin. For some reason it gives me the response 401 Unauthorized in the Network tab at the Developer tools. The Security option for the instance is None and the OpenAI key works.
Do you know a fix for this?

Node-RED Version: 4.0.2
Launcher Version: 2.6.0
Node.js Version: 20.15.0

**Comment by kazuhitoyokoi** [comment]
Could you ask your issue to FlowFuse support? This plugin is for non-customized Node-RED.
